### ISSUE TITLE
NOT AN ISSUE - seed nodes to be added to libraries/plugins/p2p/include/xgt/plugins/p2p/p2p_default_seeds.hpp

### ISSUE THREAD

**Issue by tybiboune** [xgt-network/xgt#45]
as discussed with raggi, here are a few SEED NODES to be added to 
libraries/plugins/p2p/include/xgt/plugins/p2p/p2p_default_seeds.hpp

116.202.114.157
195.201.167.19
95.216.69.92
95.216.71.199

all of them in Germany.

**Comment by obskein** [comment]
Resolved by #51
